/**
 * 开发生态域路由（卷 29 / BUILD-MANIFEST G2-01…G2-07）。默认导出 OcRoute[]。
 */
import type { OcRoute } from '../types';

export default [
  { path: '/ecosystem/sdk', name: 'eco-sdk', component: () => import('@/views/ecosystem/SdkGuide.vue'), meta: { title: 'SDK 指南', group: '分发与生态', groupOrder: 13, order: 20, icon: 'code', desc: 'TS / Java + 兼容矩阵 + 示例 + 安装命令', surface: 'registry', volume: '卷 29', manifest: 'G2-01' } },
  { path: '/ecosystem/ide', name: 'eco-ide', component: () => import('@/views/ecosystem/IdeIntegration.vue'), meta: { title: 'IDE 集成', group: '分发与生态', groupOrder: 13, order: 21, icon: 'extension', desc: '四 IDE × 7 能力矩阵（瘦客户端）', surface: 'registry', volume: '卷 29', manifest: 'G2-01' } },
  { path: '/ecosystem/ci', name: 'eco-ci', component: () => import('@/views/ecosystem/CiIntegration.vue'), meta: { title: 'CI 集成', group: '分发与生态', groupOrder: 13, order: 22, icon: 'terminal', desc: '三件套 + 退出码 0/1/2 + JSON/SARIF/Markdown + 预算必填', surface: 'registry', volume: '卷 29', manifest: 'G2-01' } },
  { path: '/ecosystem/import', name: 'eco-import', component: () => import('@/views/ecosystem/ImportWizard.vue'), meta: { title: '导入迁移', group: '分发与生态', groupOrder: 13, order: 23, icon: 'upload', desc: '六类来源 + dry-run + 迁移报告 + 快照回滚', surface: 'wizard', volume: '卷 29', manifest: 'G2-02' } },
  { path: '/ecosystem/export', name: 'eco-export', component: () => import('@/views/ecosystem/ExportCenter.vue'), meta: { title: '迁出中心', group: '分发与生态', groupOrder: 13, order: 24, icon: 'download', desc: '迁出五类 + 检查清单 + 默认脱敏（数据归用户）', surface: 'registry', volume: '卷 29', manifest: 'G2-02' } },
  { path: '/ecosystem/registry', name: 'eco-registry', component: () => import('@/views/ecosystem/RegistryBrowser.vue'), meta: { title: 'Registry 浏览', group: '分发与生态', groupOrder: 13, order: 25, icon: 'browse', desc: '搜索 + 签名 + 评分 + 安装确认 + 举报', surface: 'registry', volume: '卷 29', manifest: 'G2-03' } },
  { path: '/ecosystem/private-registry', name: 'eco-private-registry', component: () => import('@/views/ecosystem/PrivateRegistry.vue'), meta: { title: '私仓与镜像', group: '分发与生态', groupOrder: 13, order: 26, icon: 'server', desc: '私仓配置 + 离线镜像 + 同步历史 + 禁用公共源', surface: 'registry', volume: '卷 29', manifest: 'G2-03' } },
  { path: '/ecosystem/first-run', name: 'eco-first-run', component: () => import('@/views/ecosystem/FirstRunWizard.vue'), meta: { title: '首次运行向导', group: '分发与生态', groupOrder: 13, order: 27, icon: 'wizard', desc: '九步 + 每步「为什么需要」+ 可跳过 + 断点续接', surface: 'wizard', volume: '卷 29', manifest: 'G2-07' } },
  { path: '/ecosystem/search', name: 'eco-search', component: () => import('@/views/ecosystem/UnifiedSearchPage.vue'), meta: { title: '统一搜索', group: '分发与生态', groupOrder: 13, order: 28, icon: 'search', desc: '八源 + 排序 + 结果动作 + 延迟指标（P95 ≤300ms）', surface: 'registry', volume: '卷 29', manifest: 'G2-06' } },
  { path: '/ecosystem/deep-link', name: 'eco-deep-link', component: () => import('@/views/ecosystem/DeepLinkHandler.vue'), meta: { title: '深链处理', group: '分发与生态', groupOrder: 13, order: 29, icon: 'link', desc: '六动作白名单 + 签名 5 分钟 + 二次确认 + 被拦原因', surface: 'settings', volume: '卷 29', manifest: 'G2-04' } },
  { path: '/ecosystem/im-bot', name: 'eco-im-bot', component: () => import('@/views/ecosystem/ImBot.vue'), meta: { title: 'IM 机器人', group: '分发与生态', groupOrder: 13, order: 30, icon: 'robot', desc: '指令表 /status /task /cost /run + 卡片预览 + 身份绑定', surface: 'settings', volume: '卷 29', manifest: 'G2-05' } },
  { path: '/ecosystem/shell', name: 'eco-shell', component: () => import('@/views/ecosystem/ShellIntegration.vue'), meta: { title: 'Shell 集成', group: '分发与生态', groupOrder: 13, order: 31, icon: 'terminal', desc: '补全脚本 + 提示符水位 + cd 联动 + 历史回填', surface: 'settings', volume: '卷 29', manifest: 'G2-01' } },
  { path: '/ecosystem/seed-tools', name: 'eco-seed-tools', component: () => import('@/views/ecosystem/SeedTools.vue'), meta: { title: '种子数据工具', group: '分发与生态', groupOrder: 13, order: 32, icon: 'database', desc: '种子数据 + 脱敏样本 + 一键重置（可保留凭证）', surface: 'settings', volume: '卷 29', manifest: 'G2-01' } },
] as OcRoute[];
