/**
 * 企业治理域路由（卷 24 / BUILD-MANIFEST N-01…N-15）。默认导出 OcRoute[]。
 */
import type { OcRoute } from '../types';

export default [
  { path: '/enterprise/organization', name: 'ent-organization', component: () => import('@/views/enterprise/Organization.vue'), meta: { title: '组织与成员', group: '企业治理', groupOrder: 10, order: 1, icon: 'sitemap', desc: '租户/组织/团队/项目三级模型 + 成员管理 + 策略徽标', surface: 'settings', volume: '卷 24', manifest: 'N-01' } },
  { path: '/enterprise/identity', name: 'ent-identity', component: () => import('@/views/enterprise/Identity.vue'), meta: { title: '身份源（SSO/SCIM）', group: '企业治理', groupOrder: 10, order: 2, icon: 'secured', desc: 'OIDC/SAML/LDAP/SCIM + 同步日志 + 离职回收', surface: 'settings', volume: '卷 24', manifest: 'N-02' } },
  { path: '/enterprise/roles', name: 'ent-roles', component: () => import('@/views/enterprise/Roles.vue'), meta: { title: '角色与权限', group: '企业治理', groupOrder: 10, order: 3, icon: 'lock', desc: '内置 7 角色 + 自定义角色 + 资源级覆盖（追加/收窄）', surface: 'settings', volume: '卷 24', manifest: 'N-03' } },
  { path: '/enterprise/audit', name: 'ent-audit', component: () => import('@/views/enterprise/AuditLog.vue'), meta: { title: '审计日志', group: '企业治理', groupOrder: 10, order: 4, icon: 'browse', desc: '六类过滤 + 哈希链校验 + 脱敏预览导出', surface: 'settings', volume: '卷 24', manifest: 'N-04', permission: 'audit.read' } },
  { path: '/enterprise/quota', name: 'ent-quota', component: () => import('@/views/enterprise/QuotaManagement.vue'), meta: { title: '配额管理', group: '企业治理', groupOrder: 10, order: 5, icon: 'chart', desc: '七维度配额 + 继承链 + 超限策略与使用率', surface: 'settings', volume: '卷 24', manifest: 'N-05' } },
  { path: '/enterprise/cost-board', name: 'ent-cost-board', component: () => import('@/views/enterprise/CostBoard.vue'), meta: { title: '成本看板', group: '企业治理', groupOrder: 10, order: 6, icon: 'discount', desc: '趋势 + 六维归因 + 缓存折扣单列 + 预算水位', surface: 'cost', volume: '卷 31', manifest: 'N-06', permission: 'billing.read' } },
  { path: '/enterprise/budget-alerts', name: 'ent-budget', component: () => import('@/views/enterprise/BudgetAlerts.vue'), meta: { title: '预算与告警', group: '企业治理', groupOrder: 10, order: 7, icon: 'sound', desc: '50/80/100% 阈值动作 + 燃尽曲线 + 超支说明', surface: 'cost', volume: '卷 24', manifest: 'N-07' } },
  { path: '/enterprise/deployment', name: 'ent-deployment', component: () => import('@/views/enterprise/DeploymentForms.vue'), meta: { title: '部署形态', group: '企业治理', groupOrder: 10, order: 8, icon: 'server', desc: 'local / server / enterprise-server / air-gapped 四形态', surface: 'settings', volume: '卷 24', manifest: 'N-08' } },
  { path: '/enterprise/upgrade', name: 'ent-upgrade', component: () => import('@/views/enterprise/UpgradeRollback.vue'), meta: { title: '升级与回滚', group: '企业治理', groupOrder: 10, order: 9, icon: 'refresh', desc: '预检 → 灰度 → 观察 → 扩大 → 全量 → 回滚', surface: 'settings', volume: '卷 24', manifest: 'N-09' } },
  { path: '/enterprise/dlp', name: 'ent-dlp', component: () => import('@/views/enterprise/DlpRules.vue'), meta: { title: '内容治理（DLP）', group: '企业治理', groupOrder: 10, order: 10, icon: 'secured', desc: '五类规则 + 命中记录 + 阻断建议（不静默拦截）', surface: 'settings', volume: '卷 24', manifest: 'N-11' } },
  { path: '/enterprise/flags', name: 'ent-flags', component: () => import('@/views/enterprise/FeatureFlags.vue'), meta: { title: '特性开关与灰度', group: '企业治理', groupOrder: 10, order: 11, icon: 'flag', desc: '多维作用域 + 灰度比例 + 差异 + 变更审计 + 熔断开关', surface: 'settings', volume: '卷 24', manifest: 'N-12' } },
  { path: '/enterprise/residency', name: 'ent-residency', component: () => import('@/views/enterprise/Residency.vue'), meta: { title: '数据驻留与加密', group: '企业治理', groupOrder: 10, order: 12, icon: 'cloud', desc: '驻留声明 + 字段级加密 + BYOK + 跨境审批', surface: 'settings', volume: '卷 24', manifest: 'N-10、N-13' } },
  { path: '/enterprise/diagnostics', name: 'ent-diagnostics', component: () => import('@/views/enterprise/DiagnosticsBundle.vue'), meta: { title: '诊断包', group: '企业治理', groupOrder: 10, order: 13, icon: 'file-copy', desc: '项清单 + 脱敏预览 + 可选上传 + 过期删除', surface: 'settings', volume: '卷 24', manifest: 'N-14' } },
  { path: '/enterprise/self-check', name: 'ent-self-check', component: () => import('@/views/enterprise/TenantSelfCheck.vue'), meta: { title: '租户化自检', group: '企业治理', groupOrder: 10, order: 14, icon: 'check', desc: '逐域租户化清单 + 跨租户红线检查', surface: 'settings', volume: '卷 24', manifest: 'N-15' } },
] as OcRoute[];
